### ISSUE TITLE
Problems with "iojs_version is defined"

### ISSUE THREAD

**Issue by aklinkert** [William-Yeh/ansible-nodejs#3]
Hi,

I'm getting an error with this role. I've defined my playbook as follows:

```
- name: Web Servers
  hosts: webservers
  gather_facts: true
  serial: "25%"

  roles:
    - williamyeh.nodejs

  vars:
    nodejs_version: "0.12"
```

I'm getting the following error:

```
TASK [williamyeh.nodejs : install io.js with specific version] *****************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'iojs_version' is undefined"}
```

I'm using ansible version 2.0.0:

```
ansible 2.0.0 (devel 89646d4253) last updated 2015/11/15 23:41:12 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 572771d0b1) last updated 2015/11/15 23:41:16 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD e5362cc76a) last updated 2015/11/15 23:41:19 (GMT +200)
  configured module search path = Default w/o overrides
```

Do you have any clue what's going wrong?

**Comment by William-Yeh** [comment]
What is the Linux distribution (and version) of your managed host?

**Comment by aklinkert** [comment]
It's an Droplet at digital Ocean running `Ubuntu 14.04 x64 vmlinuz-3.13.0-71-generic`.

**Comment by William-Yeh** [comment]
After experimenting with Ubuntu 14.04, it works on Ansible 1.9.4, but fails on Ansible 2.1.0.

I think there are some breaking changes since Ansible 2.x with regard to (maybe?) the handling of `include` and `when: ... is defined`.  More experiments are needed.

**Comment by William-Yeh** [comment]
After experimenting with Debian 8.2, it works well on both Ansible 1.9.4 and 2.1.0.

Vagrantfile:

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "williamyeh/ansible"
  config.vm.box_version = ">= 2.1.0"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
```

playbook.yml:

``` yaml
- name: Web Servers
  hosts: all
  sudo: true
  gather_facts: true
  serial: "25%"

  roles:
    - williamyeh.nodejs

  vars:
    nodejs_version: "0.12"
```
