### ISSUE TITLE
pkgname wildcard and version can not be mixed

### ISSUE THREAD

**Issue by map7** [William-Yeh/ansible-nodejs#4]
Just trying to install nodejs 4.3.1 on a fresh debian 8.3 machine and I'm getting this error;

```
failed: [192.168.200.215] => {"failed": true}
msg: pkgname wildcard and version can not be mixed

FATAL: all hosts have already failed -- aborting

```

Here is my playbook

```
- hosts: webservers
  user: map7
  sudo: yes
  roles:
    - role: williamyeh.nodejs
      nodejs_version: "4"
```

**Comment by William-Yeh** [comment]
Thanks.

I think the issue was solved in https://github.com/William-Yeh/ansible-nodejs/commit/306f0efce7ef2198e282d591fdce0f2dbfcd3a5f

**Comment by map7** [comment]
I just updated to the latest version of your nodejs package and now when I run my playbook I get 

`ERROR: block is not a legal parameter in an Ansible task or handler`

Here is my playbook.

```
- hosts: webservers
  user: map7
  become: yes
  roles:
    - williamyeh.nodejs

  vars:
    nodejs_version: 4.0
```

I'm using ansible 1.9.4 maybe that is the problem.
